logging:
  file: logs/todo-app.log

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
  devtools:
    restart:
      additional-paths:
      additional-exclude:

endpoints:
  shutdown:
    enabled: true
  health:
    sensitive: false
    time-to-live: 1000