logging:
  file: logs/todo-app.log

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dev
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
  devtools:
    restart:
      enabled: true
      additional-paths:
      additional-exclude:

endpoints:
  shutdown:
    enabled: true
  health:
    sensitive: false
    time-to-live: 1000


management:
  port: 8081
  address: 127.0.0.1
  security:
    enabled: false