logging:
  file: logs/todo-app.log

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false

endpoints:
  shutdown:
    enabled: true